import type { NextPage } from 'next'
import useSWR from 'swr'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const fetcher = (url: String) => fetch(url.toString()).then((res) => res.json())

const Home: NextPage = () => {
  
const { data, error } = useSWR('/api/influencers', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  type Influencer = {
    "Influencer insta name": string,
    "instagram name": string,
    "category_1": string,
    "category_2": string,
    "Followers": string,
    "Audience country(mostly)": string,
    "Authentic engagement\r\n": string,
    "Engagement avg\r\n": string
}

  const groupByCategory = (arr: Array<Influencer>) => {
    let categoriesObj: Record<string, any> = {}
    for (let entry of arr) {
      const categoryName = entry["category_1"];
      const instagramName = entry["instagram name"]
      const followers = entry["Followers"]
      
      if (!categoriesObj.hasOwnProperty(categoryName)) {
        categoriesObj[categoryName] = {}
      }
      categoriesObj[categoryName] = {...categoriesObj[categoryName], [followers]: instagramName}
      
    }
    const categoriesArray = Object.entries(categoriesObj).map((entry) => [entry[0], Object.entries(entry[1]).sort()])
    const alphabetical = categoriesArray.sort((a, b) => a[0].localeCompare(b[0]));
    // console.log("TEST alphabetical", alphabetical)
    return alphabetical
   }
    
   const categoriesObj = groupByCategory(data.data)
    // console.log("TEST categoriesObj", categoriesObj)


  //  const sortByFollowers = (arr:string[]) => {
  //    let sorted = []
  //    for (let category of arr) {
  //     const byFollowers = category[1].sort((a, b) => a[0].localeCompare(b[0]));}
  //     sorted.push([category[1], byFollowers])
  //    }
  //   return sorted
  //   }

  const topByFollowers = (arr:string[]) => {
    const sorted = arr.sort()
    return sorted[0][1]
   }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<header>
  <h1>
  Influencer data
  </h1>
</header>
      <main className={styles.main}>
      <div className={styles.grid}>
      <div className={styles.card}>
      <h2 className={styles.title}>
          #1 top influencers per category, by followers
        </h2>
        {categoriesObj.map((category, i) => (
          <div key={i} className={styles.entry}>
            <h4>{category[0]}</h4>
            <h5>{topByFollowers(category[1])}</h5>
          </div>
        ))}
</div>
<div className={styles.card}>
<h2 className={styles.title}>
#1 top influencers per country, by engagement avg        </h2>
</div>
</div>
            </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/saniagarciadev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sania García
        </a>
      </footer>
    </div>
  )
}

export default Home
