import type { NextPage } from 'next'
import useSWR from 'swr'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const fetcher = (url: String) => fetch(url.toString()).then((res) => res.json())

const Home: NextPage = () => {
  
const { data, error } = useSWR('/api/influencers', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  // console.log("TEST", data.data)

  type Influencer = {
    "Influencer insta name": string,
    "instagram name": string,
    "category_1": string,
    "category_2": string,
    "Followers": string,
    "Audience country(mostly)": string,
    "Authentic engagement\r\n": string,
    "Engagement avg\r\n": string
}

  const topByCategory = (arr: Array<Influencer>) => {
    let arranged: Record<string, any> = {}  
    const sorted = arr.sort((a: Influencer, b: Influencer) => a["Influencer insta name"]	.localeCompare(b["Influencer insta name"]));
    for (let entry of sorted) {
      const categoryName = entry["category_1"];
      const instagramName = entry["instagram name"]
      const followers = entry["Followers"]
      const influencerObj = {
        instagramName,
        followers
      }
      if (!arranged.hasOwnProperty(categoryName)) {
        arranged[categoryName] = {}
      }
      arranged[categoryName] = {...arranged[categoryName], influencerObj}
      
    }
    // const categoryOnly = sorted.map((entry: Influencer) => {return entry["Influencer insta name"]})
    console.log("TEST sorted", arranged)
   }
    
   topByCategory(data.data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<header>
  <h1>
  Influencer data
  </h1>
</header>
      <main className={styles.main}>
      <div className={styles.grid}>
      <div className={styles.card}>
      <h2 className={styles.title}>
          #1 top influencers per category, by followers
        </h2>
</div>
<div className={styles.card}>
<h2 className={styles.title}>
#1 top influencers per country, by engagement avg        </h2>
</div>
</div>
            </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/saniagarciadev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sania García
        </a>
      </footer>
    </div>
  )
}

export default Home
